### ISSUE TITLE
Problème installation module SONOFF

### ISSUE THREAD

**Issue by Bouba13700** [NickDub/gladys-sonoff#1]
Bonjour,
J'ai installé votre module mais après reboot, il est impossible de démarrer Gladys. Une erreur 502 apparaît, du coup je dois supprimer le module via la console et après redémarrage de la carte tout redevient normal.
Cordialement Cyril.

**Comment by NickDub** [comment]
Bonjour,
Pourrais-tu me donner plus de détails (logs d'erreur) ?
